// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseImage: typeof import('./src/components/base/BaseImage.vue')['default']
    BaseLink: typeof import('./src/components/base/BaseLink.vue')['default']
    BaseText: typeof import('./src/components/base/BaseText.vue')['default']
    BaseVideo: typeof import('./src/components/base/BaseVideo.vue')['default']
    ButtonStyle: typeof import('./src/components/style/ButtonStyle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ImageStyle: typeof import('./src/components/style/ImageStyle.vue')['default']
    LinkStyle: typeof import('./src/components/style/LinkStyle.vue')['default']
    PageStyle: typeof import('./src/components/style/PageStyle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextStyle: typeof import('./src/components/style/TextStyle.vue')['default']
    VideoStyle: typeof import('./src/components/style/VideoStyle.vue')['default']
  }
}
